INSERT INTO questions
(id, lessonId, termId, questionText, optionA, optionB, optionC, optionD, correctOption, xpReward)
VALUES
(1, 1, 1, 'What is the email field used for copying recipients called?', 'Subject', 'Cc', 'Attachment', 'Inbox', 'B', 10),
(2, 1, 2, 'Which software is used to view webpages?', 'Browser', 'Spreadsheet', 'Compiler', 'Heat sink', 'A', 10),
(3, 1, 3, 'What is the address of a webpage or Internet resource called?', 'Cookie', 'URL', 'Toolbar', 'RAM', 'B', 10),
(4, 1, 4, 'What is the main starting page of a website commonly called?', 'Inbox', 'Homepage', 'Driver', 'Motherboard', 'B', 10),
(5, 1, 5, 'What clickable item takes a user to another page or resource?', 'Hyperlink', 'Firewall only', 'Desktop', 'Printer', 'A', 10),
(6, 1, 6, 'What type of service helps users find information on the web?', 'Search Engine', 'Text Editor', 'Expansion Card', 'ALU', 'A', 10),
(7, 1, 7, 'What action means receiving a file from the Internet to your device?', 'Upload', 'Download', 'Compile', 'Format', 'B', 10),
(8, 1, 8, 'What action means sending a local file to an online server?', 'Upload', 'Print', 'Render', 'Parse', 'A', 10),
(9, 1, 9, 'Which term refers to a readable website name such as example.com?', 'IPsec', 'Domain Name', 'Bytecode', 'USB', 'B', 10),
(10, 1, 10, 'What is the common name for unwanted bulk email messages?', 'Spam', 'Patch', 'Cache only', 'Kernel', 'A', 10),
(11, 2, 11, 'The IMAP protocol is used for what Internet service?', 'Video rendering', 'Email access', 'Memory testing', 'Local printing', 'B', 15),
(12, 2, 12, 'Which protocol is mainly used to send email?', 'SMTP', 'HDMI', 'SATA', 'NVMe', 'A', 15),
(13, 2, 13, 'What system translates domain names into IP addresses?', 'DNS', 'DMA', 'GUI', 'ECC', 'A', 15),
(14, 2, 14, 'Which protocol is commonly used by browsers to request webpages?', 'HTTP', 'ALU', 'CMOS', 'RISC', 'A', 15),
(15, 2, 15, 'What does HTTPS add to ordinary HTTP communication?', 'Encryption/security', 'More CPU cores', 'Printer support', 'File compression only', 'A', 15),
(16, 2, 16, 'What small piece of website data may be stored in a browser?', 'Cookie', 'Heat sink', 'Compiler', 'Northbridge', 'A', 15),
(17, 2, 17, 'Which protocol is commonly associated with transferring files over a network?', 'FTP', 'CISC', 'Toolbar', 'Webcam', 'A', 15),
(18, 2, 18, 'What system delivers webpages or web content to clients?', 'Web Server', 'Graphics card only', 'Text editor', 'USB cable', 'A', 15),
(19, 2, 19, 'What do HTTP, SMTP, and FTP all represent?', 'Protocols', 'Processors', 'Documents', 'Folders', 'A', 15),
(20, 2, 20, 'What term describes the data capacity of a network connection?', 'Bandwidth', 'Bytecode', 'Permissions', 'Esc', 'A', 15),
(21, 3, 21, 'What do the letters in "Ajax" stand for?', 'Advanced Java and XML', 'Asynchronous JavaScript and XML', 'Automatic JSON and XHTML', 'Applied JavaScript Extension', 'B', 20),
(22, 3, 22, 'What type of network serves content from distributed servers closer to users?', 'CDN', 'ECC', 'GUI', 'SSD', 'A', 20),
(23, 3, 23, 'Which browser mechanism controls whether a page can request resources from another origin?', 'CORS', 'BGP', 'SATA', 'Toolbar', 'A', 20),
(24, 3, 24, 'Which DNS-related technology helps verify the authenticity of DNS data?', 'DNSSEC', 'SMTP', 'DMA', 'GUI', 'A', 20),
(25, 3, 25, 'Which routing protocol exchanges route information between large Internet networks?', 'BGP', 'FTP', 'ALU', 'API', 'A', 20),
(26, 3, 26, 'Which email authentication method uses digital signatures to verify message origin?', 'DKIM', 'USB', 'Loop', 'HDMI', 'A', 20),
(27, 3, 27, 'Which API style is commonly based on resources and standard HTTP operations?', 'REST', 'SOAP only', 'CMOS', 'Folder', 'A', 20),
(28, 3, 28, 'Which web service protocol is strongly associated with XML-based messages?', 'SOAP', 'NVMe', 'Text Editor', 'RAM', 'A', 20),
(29, 3, 29, 'What value controls how long cached DNS data or packets may remain valid?', 'TTL', 'GPU', 'Query', 'Desktop', 'A', 20),
(30, 3, 30, 'Which protocol is commonly used by ping for network diagnostics?', 'ICMP', 'SMTP', 'HTML only', 'Patch', 'A', 20),
(31, 4, 31, 'The letters on the "Esc" key are an abbreviation for what?', 'Escape', 'Escort', 'Execute', 'Exchange', 'A', 10),
(32, 4, 32, 'Which input device is mainly used for typing?', 'Monitor', 'Keyboard', 'Printer', 'Speaker', 'B', 10),
(33, 4, 33, 'Which device is commonly used to move a cursor and click items?', 'Mouse', 'RAM', 'CPU', 'Web server', 'A', 10),
(34, 4, 34, 'Which device displays visual output from a computer?', 'Monitor', 'Router only', 'Keyboard', 'Heat sink', 'A', 10),
(35, 4, 35, 'Which device produces text or images on paper?', 'Printer', 'Browser', 'Loop', 'Cookie', 'A', 10),
(36, 4, 36, 'Which component is often described as the main processor of a computer?', 'CPU', 'USB', 'Folder', 'SMTP', 'A', 10),
(37, 4, 37, 'Which memory is used as temporary working memory while programs run?', 'RAM', 'ROM only', 'Printer', 'Hyperlink', 'A', 10),
(38, 4, 38, 'Which common standard is used to connect many external devices?', 'USB', 'REST', 'SQL', 'Toolbar', 'A', 10),
(39, 4, 39, 'Which device captures video input for calls or recording?', 'Webcam', 'Hard drive', 'Compiler', 'Cookie', 'A', 10),
(40, 4, 40, 'Which device is used for long-term storage of files and programs?', 'Hard Drive', 'GUI', 'Protocol', 'Window', 'A', 10),
(41, 5, 41, 'When was the first iPod released?', '1998', '2001', '2007', '2010', 'B', 15),
(42, 5, 42, 'Which processor is specialized for graphics rendering?', 'GPU', 'DNS', 'Patch', 'Folder', 'A', 15),
(43, 5, 43, 'What is the main circuit board that connects core PC components?', 'Motherboard', 'Cookie', 'Function', 'Search engine', 'A', 15),
(44, 5, 44, 'Which storage device uses flash memory and has no spinning disk?', 'SSD', 'CRT monitor', 'Printer', 'Esc key', 'A', 15),
(45, 5, 45, 'Which interface is commonly used to carry digital audio and video to a display?', 'HDMI', 'SMTP', 'CORS', 'ALU', 'A', 15),
(46, 5, 46, 'Which technology is commonly used for wired local network connections?', 'Ethernet', 'Toolbar', 'Bytecode', 'CMOS', 'A', 15),
(47, 5, 47, 'What is one independent processing unit inside a CPU called?', 'Processor Core', 'Homepage', 'File Extension', 'Cookie', 'A', 15),
(48, 5, 48, 'Which component helps draw heat away from a CPU or chip?', 'Heat Sink', 'Search Engine', 'GUI', 'REST', 'A', 15),
(49, 5, 49, 'Which interface is used to connect many internal storage drives?', 'SATA', 'Ajax', 'Document', 'DKIM', 'A', 15),
(50, 5, 50, 'What kind of board can be added to a PC to provide extra features?', 'Expansion Card', 'Webpage', 'Loop', 'Cookie', 'A', 15),
(51, 6, 51, 'What acronym describes memory transfers that bypass the CPU?', 'Direct Memory Access', 'Dynamic Memory Allocation', 'Digital Module Adapter', 'Data Mapping Array', 'A', 20),
(52, 6, 52, 'Which CPU unit performs arithmetic and logical operations?', 'ALU', 'IMAP', 'GUI', 'Cookie', 'A', 20),
(53, 6, 53, 'Which motherboard-related term is traditionally associated with storing BIOS or UEFI settings?', 'CMOS', 'REST', 'Patch', 'Folder', 'A', 20),
(54, 6, 54, 'Which memory technology can detect and correct certain data errors?', 'ECC', 'Ajax', 'Shortcut', 'Window', 'A', 20),
(55, 6, 55, 'Which chip can be configured after manufacturing for specialized hardware tasks?', 'FPGA', 'SMTP', 'Text Editor', 'Cookie', 'A', 20),
(56, 6, 56, 'Which processor design approach uses a reduced instruction set?', 'RISC', 'CORS', 'Toolbar', 'Webcam', 'A', 20),
(57, 6, 57, 'Which processor design approach uses a complex instruction set?', 'CISC', 'DNSSEC', 'Document', 'Upload', 'A', 20),
(58, 6, 58, 'Which older chipset component connected the CPU to high-speed components?', 'Northbridge', 'Footer', 'Compiler', 'Spam', 'A', 20),
(59, 6, 59, 'Which storage protocol is designed for fast SSDs over PCI Express?', 'NVMe', 'HTTP', 'GUI', 'Printer', 'A', 20),
(60, 6, 60, 'Which metric measures storage input/output operations per second?', 'IOPS', 'TTL', 'URL', 'Folder', 'A', 20),
(61, 7, 61, 'The toolbar is typically located in what part of a window?', 'Bottom', 'Top', 'Only inside a file name', 'Only in hardware', 'B', 10),
(62, 7, 62, 'What is a software application commonly called on phones and computers?', 'App', 'CPU', 'Cable', 'Monitor', 'A', 10),
(63, 7, 63, 'What is a set of instructions that a computer can run called?', 'Program', 'Domain Name', 'Keyboard', 'Heat sink', 'A', 10),
(64, 7, 64, 'What container is used to organize files?', 'Folder', 'RAM', 'SMTP', 'GPU', 'A', 10),
(65, 7, 65, 'What part of a filename usually indicates its file type?', 'File Extension', 'Processor Core', 'Search Engine', 'Cookie', 'A', 10),
(66, 7, 66, 'What is the main workspace shown after logging into an operating system called?', 'Desktop', 'Motherboard', 'DNS', 'DMA', 'A', 10),
(67, 7, 67, 'What rectangular screen area displays an app or document?', 'Window', 'USB', 'CORS', 'ALU', 'A', 10),
(68, 7, 68, 'Which software is used to edit plain text files?', 'Text Editor', 'Printer', 'Webcam', 'Router', 'A', 10),
(69, 7, 69, 'What is a copy of data kept so it can be restored later?', 'Backup', 'Bandwidth', 'Expansion Card', 'ICMP', 'A', 10),
(70, 7, 70, 'What is an electronic file containing text or other content called?', 'Document', 'Heat Sink', 'Protocol', 'GPU', 'A', 10),
(71, 8, 71, 'What term describes an electronic document?', 'File', 'Motherboard', 'Bandwidth', 'CPU', 'A', 15),
(72, 8, 72, 'What allows software components to communicate through defined rules?', 'API', 'Monitor', 'Esc', 'Printer', 'A', 15),
(73, 8, 73, 'What reusable block of code performs a specific task?', 'Function', 'Cookie', 'HDMI', 'Webcam', 'A', 15),
(74, 8, 74, 'What programming structure repeats a set of instructions?', 'Loop', 'RAM', 'SMTP', 'Toolbar only', 'A', 15),
(75, 8, 75, 'What is a request for information from a database or search system called?', 'Query', 'Heat sink', 'Domain Name', 'Keyboard', 'A', 15),
(76, 8, 76, 'What term refers to the period when a program is executing?', 'Runtime', 'Download', 'SATA', 'Cc', 'A', 15),
(77, 8, 77, 'What type of interface uses visual elements like buttons and windows?', 'GUI', 'DNSSEC', 'FPGA', 'SMTP', 'A', 15),
(78, 8, 78, 'What software update fixes bugs or improves behavior?', 'Patch', 'Printer', 'Northbridge', 'Search Engine', 'A', 15),
(79, 8, 79, 'What rules define what a user or program can access or change?', 'Permissions', 'HDMI', 'RAM', 'Spam', 'A', 15),
(80, 8, 80, 'What system tracks changes to code or files over time?', 'Version Control', 'Webcam', 'Hard Drive', 'TTL', 'A', 15),
(81, 9, 80, 'Which of the following can parse a script?', 'Firewall', 'Interpreter', 'Spreadsheet', 'Image editor', 'B', 20),
(82, 9, 80, 'Which program translates source code into another form before execution?', 'Compiler', 'Router', 'Monitor', 'Cc field', 'A', 20),
(83, 9, 80, 'What is the core part of an operating system that manages hardware resources?', 'Kernel', 'Cookie', 'HDMI', 'Hyperlink', 'A', 20),
(84, 9, 80, 'What condition occurs when processes wait on each other and cannot continue?', 'Deadlock', 'Homepage', 'USB', 'Printer queue only', 'A', 20),
(85, 9, 80, 'What bug depends on unpredictable timing between operations?', 'Race Condition', 'Domain Name', 'Heat Sink', 'Download', 'A', 20),
(86, 9, 80, 'What automatic memory management frees unused objects?', 'Garbage Collection', 'Search Engine', 'SATA', 'Cc', 'A', 20),
(87, 9, 80, 'What is intermediate code executed by a virtual machine or runtime called?', 'Bytecode', 'Bandwidth', 'Keyboard', 'Toolbar', 'A', 20),
(88, 9, 80, 'What request does a program make to the operating system kernel for a service?', 'System Call', 'Upload', 'Webcam', 'Cookie', 'A', 20),
(89, 9, 80, 'Which vulnerability involves malicious SQL inserted through user input?', 'SQL Injection', 'HTTP', 'Monitor', 'Expansion Card', 'A', 20),
(90, 9, 80, 'What is a reusable solution template for a common software design problem?', 'Design Pattern', 'Hard Drive', 'IMAP', 'Domain Name', 'A', 20);